SELECT CONCAT(NAME,'(',SUBSTRING(OCCUPATION,1,1),')') AS NAME FROM OCCUPATIONS ORDER BY NAME ASC;
SELECT CONCAT('There are a total of ','',COUNT(OCCUPATION),'    ',LOWER(OCCUPATION),'s.') AS TOTAL FROM OCCUPATIONS GROUP BY OCCUPATION ORDER BY TOTAL;
